apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartprofile-api
  labels:
    app: smartprofile-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartprofile-api
  template:
    metadata:
      labels:
        app: smartprofile-api
    spec:
      containers:
        - name: smartprofile-api
          image: shylendra2015/smartprofile-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: smartprofile-api-svc
spec:
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  selector:
    app: smartprofile-api